before_script:
 - opam update
 - opam switch -y remove gitrunner ||  echo "Opam environment clean up"
 - opam switch -y create gitrunner ocaml-base-compiler.4.10.0
 - opam pin -y dune 2.9.3
 - opam install . -y --deps-only
 - opam pin -y alt-ergo-lib https://github.com/OCamlPro/alt-ergo/archive/refs/heads/next.zip
 - opam install -y --ignore-constraints-on alt-ergo-lib alt-ergo
 - opam install -y why3
 - eval $(opam env)
 - why3 config detect
build:
  stage: build
  script:
  - make
  - make test
  - make doc
