before_script:
 - opam switch -y remove gitrunner ||  echo "Opam environment clean up"
 - opam switch -y create gitrunner ocaml-base-compiler.4.10.0
 - opam install . -y --deps-only
 - opam install opam-depext
 - apt-get install `opam depext -l alt-ergo why3`
 - opam install alt-ergo why3
 - eval $(opam env)
 - why3 config detect
build:
  stage: build
  script:
  - make
  - make test
  - make doc
