image: python3.7-alpine

prerequis:
  stage: .pre
  script:
    - opam update
    - opam switch -y remove gitrunner ||  echo "Opam environment clean up"
    - opam switch -y create gitrunner ocaml-base-compiler.5.0.0
    - opam install . -y --deps-only
    - eval $(opam env)

build:
  stage: build
  script:
    - make

test:
  stage: test
  script:
    - make test

docbuild:
  stage: .pre
  rules:
    - if: $CI_COMMIT_TITLE =~ /\[doc\]/
  script:
    - pip3 install -U pip
    - pip3 install sphinx
    - pip3 install sphinx_rtd_theme beautifulsoup4 sphinx-tabs antlr4-python3-runtime==4.7.1 pexpect sphinxcontrib-bibtex myst-parser readthedocs-sphinx-search

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TITLE =~ /\[doc\]/
  script:
    - make install
    - make deploy-html
  artifacts:
    paths:
    - public
