image: python3.7-alpine

before_script:
 - opam update
 - opam switch -y remove gitrunner ||  echo "Opam environment clean up"
 - opam switch -y create gitrunner ocaml-base-compiler.4.13.1
 - opam install . -y --deps-only
 - eval $(opam env)
 - pip3 install -U pip
 - pip3 install sphinx
 - pip3 install sphinx_rtd_theme beautifulsoup4 sphinx-tabs antlr4-python3-runtime==4.7.1 pexpect sphinxcontrib-bibtex myst-parser

pages:
  stage: deploy
  script:
  - make
  - make install
  - make test
  - make deploy-html
  artifacts:
    paths:
    - public

